# Generated by Django 5.2.12 on 2026-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, default=None, help_text='True - новостройка, False - старое здание, пусто - не указано', null=True, verbose_name='Новостройка'),
        ),
    ]
