# Generated by Django 5.2.12 on 2026-03-11 10:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер в международном формате, например: +71234567890', max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
